### ISSUE TITLE
Tapping the checkbox in a filtered view changes the following checkbox

### ISSUE THREAD

**Issue by lluchs** [evancz/elm-todomvc#1]
Steps to reproduce:

1. Add two items
2. Go to "Active"
3. Click the first item's checkbox

Result: [Screenshot](https://cloud.githubusercontent.com/assets/516527/3646278/44a6eac8-10f2-11e4-9561-979f87ac9db6.png)

**Comment by Frogglet** [comment]
So it seems this bug (or some similar variant of it) is still here. As someone who is trying to evaluate elm, it makes me nervous that it is this difficult to implement this Todo example correctly in elm. If nobody cares to fix it, perhaps you could demo the language with a similar app that is done correctly instead?

**Comment by jagare** [comment]
This is still a problem in 0.17 and the reason is again what Stilgar84 points out: reuse of the input element without checking it state. cf [https://github.com/elm-lang/virtual-dom/issues/24](https://github.com/elm-lang/virtual-dom/issues/24)

**Comment by evancz** [comment]
Should be fixed now.
