### ISSUE TITLE
No longer compiles (main expects Signal Element)

### ISSUE THREAD

**Issue by AdrianoFerrari** [evancz/elm-todomvc#14]
Cloning this and running `elm-make Todo.elm` installs 1.1.0 of core, elm-html, and virtual-dom, but I still get:

```
Error in Todo.elm:

Type Error: 'main' must have type Element or (Signal Element).

Instead 'main' has type:
    Signal.Signal Html.Html
```

Could it be that all the examples have been switched to "main gets Html", but 1.1.0 still expects Element?

**Comment by AdrianoFerrari** [comment]
Silly mistake: upgrade to elm 0.14.1 needed.

**Comment by evancz** [comment]
No worries, it was a fairly quiet announcement. Glad it's working for you again!
