### ISSUE TITLE
Why visibility is a string and not a union type?

### ISSUE THREAD

**Issue by Antontelesh** [evancz/elm-todomvc#36]
I'm new to Elm and reading code to understand language and patterns.
For me it seems like making `visibility` a union type would be better for understanding the code and type safety. Isn't it?

```
type Visibility
  = Active
  | Completed
  | All
```

**Comment by jwmerrill** [comment]
I tried making this change: https://github.com/evancz/elm-todomvc/compare/master...jwmerrill:visibility-type

It mostly worked out nicely. The compiler told me everything I needed to do after I created the Visibility type, and changed the type of Model.

However, you can't currently serialize a Union Type directly through a port, so if you make this change, the serialization to localStorage gets more complicated. I just ripped that feature out in my branch, so it isn't suitable for a PR. I think this won't be easy until https://github.com/elm-lang/elm-compiler/issues/490 is solved.

**Comment by Antontelesh** [comment]
@jwmerrill Thank you for this investigation and explanation. Now it is clear for me.
