### ISSUE TITLE
deploy to heroku don't work

### ISSUE THREAD

**Issue by zzz6519003** [evancz/elm-todomvc#37]
```
    No argument was given for the port named 'getStorage' with type:
    
        Maybe.Maybe Todo.Model

```

:+1:

**Comment by evancz** [comment]
Can you find the PR that added the button and cc the person that added it?

If we can't get ahold of this person, can you open a PR to remove the button?

**Comment by zzz6519003** [comment]
yes, sir!

use "git blame" magic

cc @srid

**Comment by evancz** [comment]
Cool, I think from here the process should be: let's do the PR to remove the button. If @srid can fix it, he can do a new PR that adds it back in a working way.

**Comment by srid** [comment]
> Cool, I think from here the process should be: let's do the PR to remove the button.

I think there should be a few days time before doing the removal, so it gives me an opportunity to respond.

**Comment by srid** [comment]
@zzz6519003 - Your title is inaccurate. Deploy to Heroku works (i.e, succeeds) - however the app is emitting the error during runtime (i.e., when accessed from browser):

```
Port Error:

    No argument was given for the port named 'getStorage' with type:
    
        Maybe.Maybe Todo.Model
    
    You need to provide an initial value!
    
    Find out more about ports here <http://elm-lang.org/learn/Ports.elm>

Open the developer console for more details.
```

**Comment by zzz6519003** [comment]
Cool, I think from here the process should be: let the app not emit the error during runtime
