### ISSUE TITLE
syntax doubt about view

### ISSUE THREAD

**Issue by neocris** [evancz/elm-todomvc#40]
i'm new to elm and have a question concerning view arguments: in main, view is called with a Signal Model as second argument but the type annotation of view refers the argument as being Model.

i have this same issue in another app i'm working to practice elm in which the compiler report this error but it seems to be working here, how can this be?

```
Function `view` is expecting the 2nd argument to be:

    { tasks : List Task }

But it is:

    Signal Model
```

**Comment by evancz** [comment]
Do you mind asking this same question on elm-discuss or in the Elm slack channel? 

  * https://groups.google.com/forum/#!forum/elm-discuss
  * http://elmlang.herokuapp.com/

I think you can get better answers in both of those places.

**Comment by evancz** [comment]
You may also be having issues if you are trying to use Elm 0.17 today. I am still working on upgrading this project to 0.17

**Comment by neocris** [comment]
thx for your input. i was not quite sure to post this here but as it seemed to me very focalized on elm-todomvc i gave it a shot. for the record i'm using elm v.0.16.0
