### ISSUE TITLE
Split into multiple files

### ISSUE THREAD

**Issue by NilsLattek** [evancz/elm-todomvc#45]
I could not find a lot of information about splitting elm code into multiple files. And it was a lot trial and error to get this to work. Especially regarding splitting the update/msg stuff into multiple files and keeping the types correctly.
It would be nice to have an example app like this which is split into multiple files/smaller components.
Would you rather create small files with ```update``` and ```view``` functions. Or split them like in the redux architecture: Have one folder for all the actions/updates and one for views...

**Comment by evancz** [comment]
I'd like to keep this one the same. I am working on some learning resources about how to break things into modules in a nice way. That will come out separately.
