### ISSUE TITLE
The 'Clear completed' button does nothing in Firefox

### ISSUE THREAD

**Issue by jhrcek** [evancz/elm-todomvc#47]
I'm able to reproduce this issue with Firefox 47 (the latest). In chrome it seems to be working fine.

**Comment by evancz** [comment]
Is this still true? I just produced a new version [here](http://evancz.github.io/elm-todomvc/). If so, what OS are you on? When you open the developer console, are you seeing any errors?

**Comment by evancz** [comment]
I bet this is resolved by #46, which I brought in a different way. I'll close. Reopen if there's still a problem (assuming you do a hard refresh to make sure you are getting the new resources).

**Comment by jhrcek** [comment]
I confirm, that now it's working fine.
