### ISSUE TITLE
Cannot run Todo from elm-reactor or serving from local server

### ISSUE THREAD

**Issue by paul-HPA** [evancz/elm-todomvc#50]
Console is revealing the following error upon launching from elm-reactor: 
```
"Todo.elm:3025 Uncaught Error: You are trying to initialize module `Todo` with an unexpected argument.
When trying to convert it to a usable Elm value, I run into this problem:

I ran into the following problems:

Expecting null but instead got: undefined
Expecting an object with a field named `entries` but instead got: undefined"
```
Same from localhost (mamp) serving index.html.

**Comment by evancz** [comment]
Try opening the browser console and running `localStorage.clear()`. Now what happens?

You may have set local storage at some other time, and it could be messing things up.

**Comment by paul-HPA** [comment]
Thank you for the quick reply Evan (I just completed the architecture tutorial and I love Elm!).  I ran that in Chrome 51.0.2704.103 but same result.  Maybe it's some other local setting...

**Comment by evancz** [comment]
Thanks :)

Do you mind working through this with someone on the Elm slack? It may be an issue, but I don't see it based on the info I have now. I bet someone there can help pin it down. Let me know what you find!

**Comment by kgashok** [comment]
You need to "Delete" the previous local storage file. After right clicking on the page, 
"Inspect" -> "Resources" -> "Local Storage" -> "Delete" the file that already exists. The screenshot below should be helpful

![screenshot 2016-07-17 at 14 07 02](https://cloud.githubusercontent.com/assets/2399010/16899610/c79784fc-4c27-11e6-920f-9d18ba40657e.png)

**Comment by paul-HPA** [comment]
Thank you both for responding, @evancz and @kgashok. Re: manually deleting the Local Storage, there is no value to delete (empty).  I will check out the slack!

**Comment by futtetennista** [comment]
@paul-HPA would you mind share your solution (if you found one)?

I'm having the same issue if I try to load the app on localhost while `elm-reactor` is running but it works without any issues if I open the file directly (so I guess it's `elm-reactor` messing up something). Deleting the `elm-stuff` folder and regenerating `elm.js` does not help and restarting `elm-reactor` also doesn't help.

**Comment by paul-HPA** [comment]
Hey @futtetennista , sorry for the delay.   I did not resolve per se; I did a clean install of the newest version of Elm and have since not re-encountered the problem.
