### ISSUE TITLE
Fails to start with reactor

### ISSUE THREAD

**Issue by hura** [evancz/elm-todomvc#8]
The app gives me the following error if I want to run it under reactor:

    Initialization Error: port 'getStorage' was not given an input!
    Open the developer console for more details.

**Comment by 4d47** [comment]
I think this issue affects more than reactor.

Using Elm Platform 0.16.0 with latest master branch.
Following *build instructions* and opening index.html in Chrome show:

```
Port Error:

    No argument was given for the port named 'getStorage' with type:
    
        Maybe.Maybe Todo.Model
    
    You need to provide an initial value!
    
    Find out more about ports here <http://elm-lang.org/learn/Ports.elm>

Open the developer console for more details.
```

Elm reactor on `Todo.elm` give the same output but the `?debug` gives:

```
_U.list is not a function
```

http://evancz.github.io/elm-todomvc/ is working but the source looks very different, I guess it's an older version of Elm and TodoMvc.

**Comment by caseyhoward** [comment]
I'm new to learning elm and decided I wanted to try running an example app. This is the first error I ran into. This hasn't worked since 2014? It concerns me as someone new to elm that the todo-mvc app doesn't even work. What needs to be done to fix this?

**Comment by kgashok** [comment]
Read this https://github.com/kgashok/elm-todomvc/blob/patch-1/README.md#troubleshooting 

I could not get the `elm-todomvc` to work directly on the Elm web console (http://www.elm-lang.org), but I got it to work on a local build. Once you have a local build, launch `index.html` directly in the browser (not through the elm-reactor).

**Comment by rattrayalex** [comment]
I got a different error (running reactor 0.17.0): 

```
Todo.elm:2959 Uncaught Error: You are trying to initialize module `Todo` with an unexpected argument.
When trying to convert it to a usable Elm value, I run into this problem:

I ran into the following problems:

Expecting null but instead got: undefined
Expecting an object with a field named `field` but instead got: undefined
```

This appeared in the JavaScript console (so much for the "no runtime errors" guarantee). It appears to work when compiled manually with `--output elm.js` but not without that (I get the same error). 

As a first-time user, I have to say this is a big turnoff (especially given the age of this issue). This appears to be a core, canonical example application for a sparsely-documented language/framework; it should work when run without special arguments.

**Comment by evancz** [comment]
Since this app uses ports, it does not get "automatically" set up with the reactor. You have to follow [the build instructions](https://github.com/evancz/elm-todomvc#build-instructions) in the README.

**Comment by kgashok** [comment]
My pull [request](https://github.com/evancz/elm-todomvc/pull/39) elaborates on how to troubleshoot this issue, and could be helpful for first timers.
